### ISSUE TITLE
Incorrect LMS/H20/LMS-sigVer-SHA256-M32 vectors

### ISSUE THREAD

**Issue by pully1** [post-quantum-cryptography/KAT#11]
Thank you very much for creating these test vectors.

Unless I am missing something (I usually am), the LMS/H20/LMS-sigVer-SHA256-M32 vectors seem to be the H5/H10 vectors instead of the H20 vectors. See the internalProjection.json file here

[KAT](https://github.com/post-quantum-cryptography/KAT/tree/main)/[LMS](https://github.com/post-quantum-cryptography/KAT/tree/main/LMS)/[H20](https://github.com/post-quantum-cryptography/KAT/tree/main/LMS/H20)/[LMS-sigVer-SHA256-M32](https://github.com/post-quantum-cryptography/KAT/tree/main/LMS/H20/LMS-sigVer-SHA256-M32)
/internalProjection.json

Thanks,
Al

**Comment by kriskwiatkowski** [comment]
Sorry for late response.
Yes, you're correct. Let me fix it.

**Comment by kriskwiatkowski** [comment]
Fixed by commit 562d43a646041e5a7b0cdebb15376d85905d8f66
